export const enum Get {
    Animate,
    AudioSource,
    Camera,
    Collide,
    Draw,
    Lifespan,
    Light,
    Mimic,
    Move,
    Named,
    PlayerControl,
    Render,
    RigidBody,
    Shake,
    Transform,
    Transform2D,
    Trigger,
}

export const enum Has {
    Animate = 1 << Get.Animate,
    AudioSource = 1 << Get.AudioSource,
    Camera = 1 << Get.Camera,
    Collide = 1 << Get.Collide,
    Draw = 1 << Get.Draw,
    Lifespan = 1 << Get.Lifespan,
    Light = 1 << Get.Light,
    Mimic = 1 << Get.Mimic,
    Move = 1 << Get.Move,
    Named = 1 << Get.Named,
    PlayerControl = 1 << Get.PlayerControl,
    Render = 1 << Get.Render,
    RigidBody = 1 << Get.RigidBody,
    Shake = 1 << Get.Shake,
    Transform = 1 << Get.Transform,
    Transform2D = 1 << Get.Transform2D,
    Trigger = 1 << Get.Trigger,
}
