const enum Component {
    Animate,
    AudioSource,
    Camera,
    Collide,
    Draw,
    Lifespan,
    Light,
    Mimic,
    Move,
    Named,
    PlayerControl,
    Render,
    RigidBody,
    Shake,
    Transform,
    Transform2D,
    Trigger,
}

export const enum Has {
    Animate = 1 << Component.Animate,
    AudioSource = 1 << Component.AudioSource,
    Camera = 1 << Component.Camera,
    Collide = 1 << Component.Collide,
    Draw = 1 << Component.Draw,
    Lifespan = 1 << Component.Lifespan,
    Light = 1 << Component.Light,
    Mimic = 1 << Component.Mimic,
    Move = 1 << Component.Move,
    Named = 1 << Component.Named,
    PlayerControl = 1 << Component.PlayerControl,
    Render = 1 << Component.Render,
    RigidBody = 1 << Component.RigidBody,
    Shake = 1 << Component.Shake,
    Transform = 1 << Component.Transform,
    Transform2D = 1 << Component.Transform2D,
    Trigger = 1 << Component.Trigger,
}
